---
title: Tuan's page
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tntr@dtu.dk
description: 'None

'
baseurl: ''
url: http://tuannt8.info
github_username: tuannt8
excerpt_separator: "<!--more-->"
markdown: kramdown
