
# Site settings
title: Computational Geometry with Applications
email: tntr@dtu.dk
description: 'None

'
baseurl: 'index.md'
url: http://tuannt8.github.io
github_username: tuannt8
excerpt_separator: "<!--more-->"
markdown: kramdown
