---
title: Computational Geometry and Life
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tuannt8@gmail.com
description: A personal journey in Geometry
baseurl: ''
url: ''
github_username: tuannt8
git_repo: tuannt8.github.io
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
gem 'jekyll-admin', group: :jekyll_plugins
