
# Site settings
title: Computational Geometry with Applications
email: tntr@dtu.dk
description: 'None

'
baseurl: ''
url: http://tuannt8.info
github_username: tuannt8
excerpt_separator: "<!--more-->"
markdown: kramdown
